server {
  port = 10001
  port = ${?SERVER_PORT}
}

db {
  url = "jdbc:postgresql://localhost:5432/calorie_ledger"
  url = ${?DB_URL}
  user = "calorie"
  user = ${?DB_USER}
  password = "calorie"
  password = ${?DB_PASSWORD}
  poolSize = 10

  admin {
    url = "jdbc:postgresql://localhost:5432/postgres"
    url = ${?DB_ADMIN_URL}
    user = "calorie"
    user = ${?DB_ADMIN_USER}
    password = "calorie"
    password = ${?DB_ADMIN_PASSWORD}
  }
}